# Setup
title:               LBVR Games
tagline:             '- Welcome to our community'
description:         'Location-Based Virtual Reality enthusiasts building in public and fostering a community of like-minded creators.'
url:
baseurl:             'https://lbvrgames.github.io/'
paginate:            5
permalink:           pretty

# About/contact
authors:
  wout:
    name:              Wout Swinkels
    url:               https://woutswinkels.github.io/
    email:             wout@lbvrgames.com
  bart:
    name:              Bart Stukken
    url:               https://0x42.be/
    email:             bart@lbvrgames.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Github
github:
  repo:               https://github.com/LBVRGames
